# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: docker_agent

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- script: |
    az login 
    az group create --location eastus2 --name myapp-rg

    az appservice plan create -g myapp-rg -n myapp-service-plan --is-linux


    az webapp create -g myapp-rg -p myapp-service-plan -n lakshya0102 --runtime "JAVA|8-jre8"
  